modLoader = "javafml"
loaderVersion = "[4,)"
source = "https://github.com/satisfyu/Vinery"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"
license = "Custom"

[[mods]]
modId = "vinery"
version = "${version}"
displayName = "[Let's Do] Vinery"
authors = "satisfy"
credits = "MissLilitu, CR-055, Jason13Official, Cristelknight, cph101dev, BaumeisterJO"
description = '''
Sun-warmed vineyards, creaking barrels and dusty bottles in a cool cellar. Grow your grapes, press your own wine and build the winery of your dreams.
'''
logoFile = "pack.png"
displayURL = "https://www.lets-do.ch"

[[dependencies.vinery]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vinery]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vinery]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vinery]]
modId = "foundation"
type = "required"
versionRange = "[1.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[incompatibleMods]]
modId = "copperative"

[[incompatibleMods]]
modId = "nethervinery"
versionRange = "<1.2.14"

[[mixins]]
config = "vinery-common.mixins.json"